name: tienda_ropa
description: Una aplicación de ejemplo para una tienda de ropa.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
